- name: variables in ansible
  hosts: localhost
  # This is Play level variables, map
  vars:
    COURSE: DevOps with AWS
    
  tasks:
  
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}"

