- name: variables in ansible
  hosts: local host
  # This is Play level variables, map
  vars:
    COURSE: DevOps with AWS
    TRAINER: Sivakumar
    DURATION: 110HRS
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}"